### ISSUE TITLE
Players can see you floating. 

### ISSUE THREAD

**Issue by Summerxo** [manups4e/esx_spectate-with_player_control#2]
Not sure if this is FiveM or the script but got this going on when spectating. It will show me in T pose and visible. At current artifact March 25.

https://imgur.com/a/c9caext

**Comment by Summerxo** [comment]
Here is a fix >_>

Under line 302 put:
SetEntityVisible(playerPed, false)

**Comment by manups4e** [comment]
added and fixed thanks
