### ISSUE TITLE
Attempt to index a nil value

### ISSUE THREAD

**Issue by Macgeo23** [manups4e/esx_spectate-with_player_control#4]
Hi,

Esx_spectate working in few days, now i can't see the players on the server i have just the menu open and i can't really undestrand what happen: 
![image](https://user-images.githubusercontent.com/53795760/87591524-c0591f80-c6e8-11ea-9dab-584d77ebbc0e.png)

someone can help me :) ? 

Thanks

**Comment by manups4e** [comment]
the problem might be related to onesync and its 300 points range.. can't do much about it..

**Comment by Macgeo23** [comment]
Thanks for your anwser i already change to onesync. But the other problem i have right now all the players can have the access to spectate other players .. and i didn't change anything all the access it's taff only 
Do you know anything about it ?

**Comment by manups4e** [comment]
u updated to latest esx that doesn't use groups in db but passed to cfg ace permissions.. just add a server callback to check if the player has permission
